// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzyZ8QMSCR6tFAkWc69do1SyWhWYGi0EY',
    appId: '1:203669591220:web:1634054eba6e2a23bab3e1',
    messagingSenderId: '203669591220',
    projectId: 'ha-pj-a27a8',
    authDomain: 'ha-pj-a27a8.firebaseapp.com',
    storageBucket: 'ha-pj-a27a8.appspot.com',
    measurementId: 'G-BG4TFTGW2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqr5mpHne1SGxFX6O7YV3pCMTPgBIBVx4',
    appId: '1:203669591220:android:bc4994190c3f584cbab3e1',
    messagingSenderId: '203669591220',
    projectId: 'ha-pj-a27a8',
    storageBucket: 'ha-pj-a27a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApQVGHTg0_k3BgQTD_V74i76apTheY4TE',
    appId: '1:203669591220:ios:349101ebe58ef9d8bab3e1',
    messagingSenderId: '203669591220',
    projectId: 'ha-pj-a27a8',
    storageBucket: 'ha-pj-a27a8.appspot.com',
    iosClientId: '203669591220-otkiudn28dae72cgcrp86bl3ol5sme9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelAppYtb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApQVGHTg0_k3BgQTD_V74i76apTheY4TE',
    appId: '1:203669591220:ios:349101ebe58ef9d8bab3e1',
    messagingSenderId: '203669591220',
    projectId: 'ha-pj-a27a8',
    storageBucket: 'ha-pj-a27a8.appspot.com',
    iosClientId: '203669591220-otkiudn28dae72cgcrp86bl3ol5sme9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelAppYtb',
  );
}
